package:
  name: bertax
  version: 0.1

source:
  path: ../

build:
  number: 8
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy >=0.14
    - keras >=2.4.3
    - tensorflow-gpu >=2.3.0
    - pyyaml
    - h5py

about:
  home: https://github.com/rnajena/bertax
  summary: DNA sequence taxonomy prediction
  license: MIT
